FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.json medusa-config.ts ./

RUN npm ci --omit=dev --legacy-peer-deps --no-audit --no-fund --registry=https://registry.npmmirror.com \
  && npm cache clean --force

COPY .medusa ./.medusa
COPY .medusa/server/src/medusa-config.js ./medusa-config.js
COPY src ./src

EXPOSE 9000

CMD ["npm", "start"]
